### ISSUE TITLE
Plugin does not work for Google Test in CLion 2018.2

### ISSUE THREAD

**Issue by dschlegel** [anantapalani/clion-cuda-run-patcher#6]
When trying to use the Plugin with a Google Test Run Configuration CLion still tries to launch the cmake_device_link.o.

**Comment by anantapalani** [comment]
This is because the code only supports standard Run and Debug projects. If you attach a minimal project with a Google Test Run Configuration I'll look at adding support.

**Comment by anantapalani** [comment]
This issue should be fixed in v1.2.0. You will need to update to CLion 2018.3. The plugin is pending approval in the Jetbrain's plugin repository, but if you want to manually install it you can do so using the [released .jar](https://github.com/anantapalani/clion-cuda-run-patcher/releases/tag/v1.2.0) here on GitHub.
